-- AfterBuddy - Initial Schema Migration
-- Requires PostgreSQL 16 + PostGIS extension

BEGIN;

-- Spatial extension
CREATE EXTENSION IF NOT EXISTS postgis;

-- Sessions table (persistent backup of Redis sessions)
CREATE TABLE IF NOT EXISTS sessions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '24 hours',
    status      TEXT NOT NULL DEFAULT 'open'  -- open | voting | closed
);

-- Static metro stations (populated by seed script)
CREATE TABLE IF NOT EXISTS stations (
    id      SERIAL PRIMARY KEY,
    nom     TEXT NOT NULL,
    ligne   TEXT NOT NULL,
    geom    GEOMETRY(Point, 4326) NOT NULL
);

CREATE INDEX IF NOT EXISTS stations_geom_idx ON stations USING GIST (geom);

-- Participants per session
CREATE TABLE IF NOT EXISTS participants (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    nom         TEXT NOT NULL,
    station_id  INTEGER NOT NULL REFERENCES stations(id),
    geom        GEOMETRY(Point, 4326) NOT NULL,
    joined_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS participants_session_idx ON participants (session_id);
CREATE INDEX IF NOT EXISTS participants_geom_idx    ON participants USING GIST (geom);

-- Suggestions generated by GeoEngine
CREATE TABLE IF NOT EXISTS suggestions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    nom         TEXT NOT NULL,
    type        TEXT NOT NULL DEFAULT 'bar',   -- bar | cafe | restaurant
    address     TEXT,
    geom        GEOMETRY(Point, 4326) NOT NULL,
    osm_id      TEXT,
    votes       INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS suggestions_session_idx ON suggestions (session_id);

-- Votes (one per participant per session)
CREATE TABLE IF NOT EXISTS votes (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id      UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    participant_id  UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    suggestion_id   UUID NOT NULL REFERENCES suggestions(id) ON DELETE CASCADE,
    voted_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (session_id, participant_id)
);

CREATE INDEX IF NOT EXISTS votes_session_idx ON votes (session_id);

-- Nightlife zones (static "vibe" reference points — pre-seeded)
CREATE TABLE IF NOT EXISTS vibe_zones (
    id      SERIAL PRIMARY KEY,
    nom     TEXT NOT NULL,
    geom    GEOMETRY(Point, 4326) NOT NULL,
    radius  INTEGER NOT NULL DEFAULT 800  -- metres
);

CREATE INDEX IF NOT EXISTS vibe_zones_geom_idx ON vibe_zones USING GIST (geom);

-- Seed vibe zones
INSERT INTO vibe_zones (nom, geom, radius) VALUES
    ('Bastille',           ST_SetSRID(ST_MakePoint(2.3692, 48.8533), 4326), 900),
    ('Oberkampf',          ST_SetSRID(ST_MakePoint(2.3729, 48.8650), 4326), 700),
    ('Pigalle',            ST_SetSRID(ST_MakePoint(2.3341, 48.8836), 4326), 800),
    ('République',         ST_SetSRID(ST_MakePoint(2.3624, 48.8672), 4326), 800),
    ('Canal Saint-Martin', ST_SetSRID(ST_MakePoint(2.3624, 48.8723), 4326), 700),
    ('Marais',             ST_SetSRID(ST_MakePoint(2.3573, 48.8585), 4326), 900),
    ('Saint-Germain',      ST_SetSRID(ST_MakePoint(2.3324, 48.8537), 4326), 800),
    ('Montmartre',         ST_SetSRID(ST_MakePoint(2.3431, 48.8867), 4326), 700),
    ('Châtelet',           ST_SetSRID(ST_MakePoint(2.3471, 48.8585), 4326), 900),
    ('Nation',             ST_SetSRID(ST_MakePoint(2.3961, 48.8483), 4326), 700),
    ('Belleville',         ST_SetSRID(ST_MakePoint(2.3767, 48.8720), 4326), 700),
    ('Buttes-aux-Cailles', ST_SetSRID(ST_MakePoint(2.3519, 48.8277), 4326), 600),
    ('Montparnasse',       ST_SetSRID(ST_MakePoint(2.3220, 48.8422), 4326), 800),
    ('Grands Boulevards',  ST_SetSRID(ST_MakePoint(2.3489, 48.8714), 4326), 700)
ON CONFLICT DO NOTHING;

COMMIT;
